# Generated by Django 2.2.6 on 2019-10-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
