# Generated by Django 2.2.6 on 2019-10-23 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0005_message_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
