# Generated by Django 2.2.6 on 2019-10-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0006_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('yourmessage', models.TextField()),
            ],
        ),
    ]
